stages:
  data_ingestion:
    cmd: python src/CNNproject/pipeline/stage_01_data_ingestion.py
    deps:
    - src/CNNproject/pipeline/stage_01_data_ingestion.py
    - config/config.yaml
    outs:
    - artifacts/data_ingestion/Chicken-fecal-images

  preapare_base_model:
    cmd: python src/CNNproject/pipeline/stage_02_preapare_base_model.py
    deps:
    - src/CNNproject/pipeline/stage_02_preapare_base_model.py
    - config/config.yaml
    params:
    - IMAGE_SIZE
    - INCLUDE_TOP
    - CLASSES
    - WEIGHTS
    - LEARNING_RATE
    outs:
    - artifacts/prepare_base_model

  training:
  cmd: python src/CNNproject/pipeline/stage_03_training.py
  deps:
  - src/CNNproject/pipeline/stage_03_training.py
  - src/CNNproject/components/prepare_callback.py
  - config/config.yaml
  - artifacts/data_ingestion/Chicken-fecal-images
  - artifacts/prepare_base_model
  params:
  - IMAGE_SIZE
  - EPOCHS
  - BATCH_SIZE
  - AUGMENTATION
  outs: 
  - artifacts/training/model.h5

  evaluation: 
  cmd: python src\CNNproject\pipeline\stage_04_evaluation.py
  deps: 
    - src\CNNproject\pipeline\stage_04_evaluation.py
    - artifacts/data_ingestion/Chicken-fecal-images
    - artifacts/training/model.h5
    - artifacts\test_data\test_data.pkl
  params: 

